language: python
python:
  - 2.7
  - 3.5
env:
  - ANALYTICS_SETTINGS_FILE=./config.ini
install: 
  - pip install --upgrade deps/scielojcr-1.3.0-py2.py3-none-any.whl
  - python setup.py install
script:
  - python setup.py test
before_script:
  - cp ./development.ini-TEMPLATE ./config.ini
